print("Введите вид питомца:")
typePet = input()
print("Введите возраст питомца: ")
age = input()
print("Введите кличку питомцу: ")
name = input()
print("Это ", typePet, ' по кличке "', name, '". Возраст: ', age, " года.", sep="")